apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openprime-postgres.fullname" . }}-auth
  labels:
    {{- include "openprime-postgres.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.auth.postgresPassword | b64enc }}